version: "2"

linters:
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck

run:
  timeout: 5m
